spring.application.name=minimarket
server.port=8080

# Configuraci�n de H2 en memoria
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

# Configuraci�n de JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Configuracion JWT
jwt.secret=j945hg0u89438hf9r8u39ru834hf9f8ru39eu2
jwt.expiration=3600000

